import { Patient, SurveyResponse, CallAttempt } from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    PatientID: 'PAT-001',
    MRN: 'MRN-8401',
    PatientName: 'Elena Rostova',
    PhoneNumber: '+1 (555) 123-4567',
    CareManager: 'Sarah Jenkins, RN',
    Provider: 'Dr. Gregory House',
    ServiceType: 'CCM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'Paciente con hipertensión severa y diabetes tipo 2. Requiere llamadas a media mañana.'
  },
  {
    PatientID: 'PAT-002',
    MRN: 'MRN-3302',
    PatientName: 'Mateo Fernández',
    PhoneNumber: '+1 (555) 987-6543',
    CareManager: 'Sarah Jenkins, RN',
    Provider: 'Dr. Gregory House',
    ServiceType: 'RPM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'Monitoreo remoto de presión arterial. Paciente suele responder rápido.'
  },
  {
    PatientID: 'PAT-003',
    MRN: 'MRN-1129',
    PatientName: 'Sofía Al-Jamil',
    PhoneNumber: '+1 (555) 234-5678',
    CareManager: 'John Davis, NP',
    Provider: 'Dra. Allison Cameron',
    ServiceType: 'CCM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'Paciente de edad avanzada. Prefiere que su hija esté presente durante la llamada si es posible.'
  },
  {
    PatientID: 'PAT-004',
    MRN: 'MRN-4491',
    PatientName: 'Jackson Briggs',
    PhoneNumber: '+1 (555) 876-5432',
    CareManager: 'John Davis, NP',
    Provider: 'Dra. Allison Cameron',
    ServiceType: 'RPM',
    Status: 'Call Back',
    LastSurveyDate: '2026-05-15',
    Notes: 'Monitoreo de oxímetro de pulso para EPOC. Programar llamada para después de las 4 PM.'
  },
  {
    PatientID: 'PAT-005',
    MRN: 'MRN-7250',
    PatientName: 'Lucía Méndez',
    PhoneNumber: '+1 (555) 345-6789',
    CareManager: 'Sarah Jenkins, RN',
    Provider: 'Dr. Gregory House',
    ServiceType: 'CCM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'Insuficiencia cardíaca congestiva. Control estricto de medicamentos es prioritario.'
  },
  {
    PatientID: 'PAT-006',
    MRN: 'MRN-5582',
    PatientName: 'Chen Wei',
    PhoneNumber: '+1 (555) 765-4321',
    CareManager: 'John Davis, NP',
    Provider: 'Dr. Eric Foreman',
    ServiceType: 'RPM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'RPM de glucómetro celular. El paciente está familiarizado con la aplicación móvil.'
  },
  {
    PatientID: 'PAT-007',
    MRN: 'MRN-9021',
    PatientName: 'Marcus Aurelius',
    PhoneNumber: '+1 (555) 456-7890',
    CareManager: 'Maria Gomez, RN',
    Provider: 'Dr. Eric Foreman',
    ServiceType: 'CCM',
    Status: 'Completed',
    LastSurveyDate: '2026-06-05',
    Notes: 'Muy satisfecho con el seguimiento mensual de dolor crónico.'
  },
  {
    PatientID: 'PAT-008',
    MRN: 'MRN-1011',
    PatientName: 'Amina Diop',
    PhoneNumber: '+1 (555) 654-3210',
    CareManager: 'Maria Gomez, RN',
    Provider: 'Dra. Allison Cameron',
    ServiceType: 'RPM',
    Status: 'No Answer',
    LastSurveyDate: '—',
    Notes: 'Fallas constantes para contactar. Intentar marcar en horario de almuerzo.'
  },
  {
    PatientID: 'PAT-009',
    MRN: 'MRN-2015',
    PatientName: 'Liam O\'Connor',
    PhoneNumber: '+1 (555) 567-8901',
    CareManager: 'Sarah Jenkins, RN',
    Provider: 'Dr. Gregory House',
    ServiceType: 'CCM',
    Status: 'Pending',
    LastSurveyDate: '—',
    Notes: 'Manejo coordinado de artritis reumatoide y asma.'
  },
  {
    PatientID: 'PAT-010',
    MRN: 'MRN-3049',
    PatientName: 'Emma Watson',
    PhoneNumber: '+1 (555) 543-2109',
    CareManager: 'Maria Gomez, RN',
    Provider: 'Dr. Eric Foreman',
    ServiceType: 'RPM',
    Status: 'Declined',
    LastSurveyDate: '2026-05-20',
    Notes: 'Rehusó inicialmente por falta de tiempo. Volver a sugerir para ver si cambió de parecer.'
  }
];

export const INITIAL_RESPONSES: SurveyResponse[] = [
  {
    ResponseID: 'RESP-001',
    PatientID: 'PAT-007',
    PatientName: 'Marcus Aurelius',
    SurveyDate: '2026-06-05',
    SurveyTime: '10:30 AM',
    SurveyorName: 'Sandra',
    Provider: 'Dr. Eric Foreman',
    MRN: 'MRN-9021',
    PhoneNumber: '+1 (555) 456-7890',
    CareManager: 'Maria Gomez, RN',
    ServiceType: 'CCM',
    OverallSatisfactionScore: 5,
    HelpsManageHealth: 'Sí',
    CareManagerSatisfactionScore: 5,
    ClearExplanation: 'Sí',
    FollowUpOnHealthNeeds: 'Sí',
    EasyCommunication: 'Sí',
    EasyToTakeMeasurements: 'No aplica',
    WouldRecommendService: 'Sí',
    WhatPatientLikesMost: 'La atención es constante.',
    WhatCouldBeImproved: 'Nada.',
    CallStatus: 'Completed',
    FollowUpNeeded: 'No',
    InternalNotes: 'Completado sin incidentes.',
    generalSatisfactionScore: 5,
    generalSatisfactionStars: 5,
    generalSatisfactionLabel: 'Excellent Satisfaction',
    followUpRequired: false,
    followUpReasons: '',
    scoreCalculatedAt: '2026-06-05T10:30:00.000Z',
    scoreVersion: 'v1.0'
  },
  {
    ResponseID: 'RESP-002',
    PatientID: 'PAT-004',
    PatientName: 'Jackson Briggs',
    SurveyDate: '2026-05-15',
    SurveyTime: '04:30 PM',
    SurveyorName: 'Sandra',
    Provider: 'Dra. Allison Cameron',
    MRN: 'MRN-4491',
    PhoneNumber: '+1 (555) 876-5432',
    CareManager: 'John Davis, NP',
    ServiceType: 'RPM',
    OverallSatisfactionScore: 4,
    HelpsManageHealth: 'Sí',
    CareManagerSatisfactionScore: 5,
    ClearExplanation: 'Sí',
    FollowUpOnHealthNeeds: 'Sí',
    EasyCommunication: 'Sí',
    EasyToTakeMeasurements: 'Sí',
    WouldRecommendService: 'Sí',
    WhatPatientLikesMost: 'El oxímetro me ayuda.',
    WhatCouldBeImproved: 'La app a veces demora en subir.',
    CallStatus: 'Completed',
    FollowUpNeeded: 'No',
    InternalNotes: 'Satisfecho.',
    generalSatisfactionScore: 4.8,
    generalSatisfactionStars: 5,
    generalSatisfactionLabel: 'Excellent Satisfaction',
    followUpRequired: false,
    followUpReasons: '',
    scoreCalculatedAt: '2026-05-15T16:30:00.000Z',
    scoreVersion: 'v1.0'
  }
];

export const INITIAL_ATTEMPTS: CallAttempt[] = [
  {
    AttemptID: 'ATT-001',
    Date: '2026-06-05',
    Time: '10:30 AM',
    SurveyorName: 'Sandra',
    Provider: 'Dr. Eric Foreman',
    MRN: 'MRN-9021',
    PatientName: 'Marcus Aurelius',
    PhoneNumber: '+1 (555) 456-7890',
    CareManager: 'Maria Gomez, RN',
    CallResult: 'Completed',
    Notes: 'Llamada exitosa, completó encuesta.'
  },
  {
    AttemptID: 'ATT-002',
    Date: '2026-06-08',
    Time: '11:45 AM',
    SurveyorName: 'Sandra',
    Provider: 'Dra. Allison Cameron',
    MRN: 'MRN-1011',
    PatientName: 'Amina Diop',
    PhoneNumber: '+1 (555) 654-3210',
    CareManager: 'Maria Gomez, RN',
    CallResult: 'No Answer',
    Notes: 'No contesta, dejó buzón de voz.'
  },
  {
    AttemptID: 'ATT-003',
    Date: '2026-05-20',
    Time: '02:15 PM',
    SurveyorName: 'Sandra',
    Provider: 'Dr. Eric Foreman',
    MRN: 'MRN-3049',
    PatientName: 'Emma Watson',
    PhoneNumber: '+1 (555) 543-2109',
    CareManager: 'Maria Gomez, RN',
    CallResult: 'Declined',
    Notes: 'Rehusó inicialmente por falta de tiempo.'
  },
  {
    AttemptID: 'ATT-004',
    Date: '2026-05-15',
    Time: '04:30 PM',
    SurveyorName: 'Sandra',
    Provider: 'Dra. Allison Cameron',
    MRN: 'MRN-4491',
    PatientName: 'Jackson Briggs',
    PhoneNumber: '+1 (555) 876-5432',
    CareManager: 'John Davis, NP',
    CallResult: 'Completed',
    Notes: 'Llamada exitosa, completó encuesta.'
  }
];
